#!/usr/bin/env python3
from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT_ENTRY_DOCS = [
    "AGENTS.md",
    "PROJECT.md",
    "ARCHITECTURE.md",
    "DESIGN.md",
    "FRONTEND.md",
    "PLANS.md",
    "QUALITY_SCORE.md",
    "RELIABILITY.md",
    "SECURITY.md",
]

GENERATED_OUTPUTS = {
    "docs/generated/repo-inventory.md": "repo_inventory",
    "docs/generated/command-inventory.md": "command_inventory",
}

SUBSYSTEMS = [
    ("llm-wiki/", "skill、references、Python harness scripts"),
    ("audit-shared/", "web 与 plugin 共用的 audit schema / serializer"),
    ("web/", "本地 viewer"),
    ("plugins/obsidian-audit/", "Obsidian audit plugin"),
    ("docs/", "repo-level system of record"),
]

DOC_AREAS = [
    ("docs/design-docs/", "设计原则与长期设计 memo"),
    ("docs/exec-plans/active/", "当前 active execution plans"),
    ("docs/exec-plans/completed/", "已完成计划归档"),
    ("docs/product-specs/", "真实子系统短规格"),
    ("docs/generated/", "脚本生成 inventories"),
    ("docs/references/", "repo-side references catalog"),
]

REPO_WORKSPACE_COMMANDS = [
    "python3 llm-wiki/scripts/generate_repo_inventory.py .",
    "python3 llm-wiki/scripts/lint_repo_workspace.py .",
    "python3 -m py_compile llm-wiki/scripts/*.py",
]

RUNTIME_COMMANDS = [
    'python3 llm-wiki/scripts/scaffold.py <workbench-root> "<title>"',
    "python3 llm-wiki/scripts/harness.py preflight <workbench-root>",
    "python3 llm-wiki/scripts/harness.py health <workbench-root>",
    "python3 llm-wiki/scripts/harness.py postflight <workbench-root>",
    "python3 llm-wiki/scripts/lint_wiki.py <workbench-root>",
    "python3 llm-wiki/scripts/audit_review.py <workbench-root> --open",
]

PACKAGE_JSONS = [
    ("audit-shared", "audit-shared/package.json"),
    ("web", "web/package.json"),
    ("plugins/obsidian-audit", "plugins/obsidian-audit/package.json"),
]


def read_json(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def render_repo_inventory(root: Path) -> str:
    lines: list[str] = [
        "# Repo Inventory",
        "",
        "> Generated by `python3 llm-wiki/scripts/generate_repo_inventory.py .`",
        "> Do not edit manually.",
        "",
        "## Root Entry Docs",
        "",
    ]

    for doc in ["README.md", *ROOT_ENTRY_DOCS]:
        status = "present" if (root / doc).exists() else "missing"
        lines.append(f"- `{doc}`: {status}")

    lines.extend(["", "## Top-Level Subsystems", "", "| Path | Role |", "| --- | --- |"])
    for rel, role in SUBSYSTEMS:
        lines.append(f"| `{rel}` | {role} |")

    lines.extend(["", "## Docs Areas", "", "| Path | Role |", "| --- | --- |"])
    for rel, role in DOC_AREAS:
        lines.append(f"| `{rel}` | {role} |")

    return "\n".join(lines) + "\n"


def render_command_inventory(root: Path) -> str:
    lines: list[str] = [
        "# Command Inventory",
        "",
        "> Generated by `python3 llm-wiki/scripts/generate_repo_inventory.py .`",
        "> Do not edit manually.",
        "",
        "## Repo Workspace",
        "",
    ]

    for command in REPO_WORKSPACE_COMMANDS:
        lines.append(f"- `{command}`")

    lines.extend(["", "## Runtime Harness", ""])
    for command in RUNTIME_COMMANDS:
        lines.append(f"- `{command}`")

    for package_name, package_path in PACKAGE_JSONS:
        package = read_json(root / package_path)
        scripts = package.get("scripts", {})
        lines.extend(["", f"## `{package_name}` npm scripts", ""])
        for name in sorted(scripts):
            lines.append(f"- `cd {package_name} && npm run {name}`")
            lines.append(f"  - `{scripts[name]}`")

    return "\n".join(lines) + "\n"


def build_outputs(root: Path) -> dict[str, str]:
    return {
        "docs/generated/repo-inventory.md": render_repo_inventory(root),
        "docs/generated/command-inventory.md": render_command_inventory(root),
    }


def write_outputs(root: Path) -> list[Path]:
    written: list[Path] = []
    for rel_path, content in build_outputs(root).items():
        out_path = root / rel_path
        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_text(content, encoding="utf-8")
        written.append(out_path)
    return written


def main(argv: list[str]) -> int:
    root = Path(argv[1] if len(argv) > 1 else ".").resolve()
    written = write_outputs(root)
    for path in written:
        print(path.relative_to(root))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
